const projectsData = [
    {
        id: 1,
        title: "SAPIEN",
        type: "Developed at the Rochester Human-Computer Interaction Lab",
        thumbnail: "../../files/img/projects/project_1_thumbnail.png",
        content: `
        <p>
            Related paper: <a href="https://arxiv.org/abs/2308.03022" id="hyperlink" target="_blank">SAPIEN: Affective Virtual Agents Powered by Large Language Models</a>
            <h3>Introduction</h3>
            SAPIEN (Synthetic Anthropomorphic Personal Interaction ENgine) is a language model-driven coaching platform capable of engaging in open-domain conversations in real-time with users in multiple languages. This high-fidelity virtual agent platform represents a significant contribution in artificial intelligence and human-computer interaction. The project was inspired by ongoing research at the Rochester Human-Computer Interaction Lab, which involved creating virtual avatars that replicate the speech of actors portraying cancer patients to train medical students for difficult conversations. With the power of today's large language models, we realized that this technology could be easily adapted and applied to any use case that involves conversation practice.
            <br><br>
            <h3>Platform Usage</h3>
            To use the platform, users navigate to the website and select a use case, such as interview practice, foreign language speaking practice, or simulating a social scenario. Based on the chosen use case, users set parameters such as the job description, resume, context of the social scenario, and the language to be practiced. Then, users can pick one of the 30+ virtual characters of varying ages, genders, and backgrounds. Once set up, the conversation begins as a video call. SAPIEN can simulate emotions reflected in the virtual agent's voice and facial expressions. Moreover, it offers users the option to personalize the virtual agent according to their preferences, including the choice of the agent's personality, background, and conversational context. I played a key role in the research team, significantly contributing to the project's development and its deployment as a website platform.
            <br><br>
            <h3>Technical Details and AI Integration</h3>
            Utilizing state-of-the-art AI models, SAPIEN virtual agents provide a nuanced and immersive experience. The Speech-to-Text and Text-to-Speech models come from Microsoft Cognitive Services, ensuring high-quality audio processing. The agent fluently converses in various languages and accurately reflects emotional states. We integrated the capability of mimicking seven basic emotions such as Neutral, Happy, Sad, Angry, Surprised, Afraid, and Disgusted, which significantly enhances the interaction experience and makes it more expressive. For the chat functionality, we use GPT-3.5 for its speed and responsiveness, while GPT-4 is employed for post-conversation feedback, leveraging its superior text quality to provide detailed and insightful analysis.
            <br><br>
            <h3>Personalized Feedback and Applications</h3>
            Upon concluding their interaction with the SAPIEN virtual agent, users may choose to have their conversation analysed to gain personalized feedback on their communication skills. This feedback derives from the conversation's transcript, analysed in relation to a user's specified goal. It identifies their communicative strengths and weaknesses, providing actionable recommendations for improvement. This mechanism leverages the flexibility of the virtual agent's persona and adaptability to a range of applications, including language learning, communication training, and professional applications such as healthcare, sales, and leadership training.
            <br><br>
            <h3>My Contributions and Technical Responsibilities</h3>
            I contributed to the task of designing user experiences, particularly the customization of intellectual and emotional traits of AI agents, initiating dynamic conversations, and automated feedback. My responsibilities also included implementing unique features for each use case, such as an internal job search engine, a resume parser to gather user information, and temporarily capturing webcam data to infer the user's emotions for more emotionally aware conversations. Additionally, I managed the deployment on an AWS EC2 instance, as the virtual human is a MetaHuman from Unreal Engine 5 and requires significant compute power to run and scale. I also set up the Apache server to support this infrastructure. My work extended to addressing the responsible use of this technology, considering the ethical implications of such realistic virtual agent representations.
            <br><br>
            <h3>Vision and Ethical Considerations</h3>
            We envisaged SAPIEN as a powerful tool designed to help people adapt by fostering human skills through AI. SAPIEN aims to enhance our capacity for communication, empathy, and understanding while prioritizing user safety and ethical considerations. This includes not retaining memory of previous interactions, limiting conversations to a 10-minute timeframe with an 8-minute warning, and allowing virtual agents to terminate calls if desired. While many focus on the hypothetical scenario of AI replacing humans, this project achieves the opposite by promoting human skills and making humans more human. This project highlights the potential of Large Language Models and human-computer interaction, setting a new standard for virtual human-based learning and communication development.
        </p>`
    },
    {
        id: 2,
        title: "Hi5",
        type: "Developed at the Rochester Human-Computer Interaction Lab",
        thumbnail: "../../files/img/projects/project_2_thumbnail.png",
        content: `
        <p>
            Related paper: Hi5 ✋: 2D Hand Pose Estimation with Zero Human Annotation
            <h3>Introduction</h3>
            Hi5 is a synthetic hand dataset with pixel-perfect coordinates, created in a game engine, designed specifically for accurate pose estimation. This project was my very first undertaking when I joined the Rochester Human-Computer Interaction Lab. At the time, the team was developing a Parkinson's symptom screening tool website to make neurological assessments more accessible to the elderly and economically disadvantaged, providing a platform to guide them towards the right resources. One of the key tasks in the screening process was a motor test, requiring users to perform specific hand movements, such as finger tapping, to detect potential hand tremors. Given that older individuals often struggle with technology, their hands might go off-webcam or be in low-light conditions, causing Google's Mediapipe model for hand pose estimation to fail. This challenge led to the creation of Hi5, aiming to overcome these limitations and ensure robust hand pose tracking.
            <br><br>
            <h3>Challenges and Motivation</h3>
            The process of crafting an accurate and versatile dataset for AI modeling is often confronted with significant time and financial constraints. Traditional methods typically involve possessing substantial budgets to employ human labelers who manually identify and annotate each point of interest. During our research, we also observed a lack of diversity in many existing datasets, causing models trained on them to perform better on certain races. This added an extra dimension to our process, making the Hi5 project a breakthrough by leveraging technology to generate a synthetic dataset that bypasses these limitations and ensures greater inclusivity.
            <br><br>
            <h3>Methodology</h3>
            Our methodology initially involved using a Leap Motion controller to record hand animations, which were later retextured automatically during the data creation process. However, we soon encountered limitations in the Leap Motion's ability to capture more complex poses. To address this, I manually animated the hand to perform over 40 poses, selected from Facebook's paper on hand pose estimation. Additionally, we crafted 12 different 3D hand models, factoring in gender and six significant skin tones based on ITA values. This effort significantly increased the inclusivity and representativeness of the dataset and the robustness of the models we trained.
            <br><br>
            <h3>Data Augmentation</h3>
            We found that heavily augmenting the data made the model more robust, especially in low-light conditions. All the hands originated from 3D left-hand meshes, but we horizontally flipped half of the images to create "right" hands. Additionally, the randomized nature of the camera angles, zoom levels, and cropping during data augmentation allowed us to collect perfect pose estimations even for synthetic hand images with missing fingers outside the frame. The main augmentations can be split into color space operations and geometrical operations. Geometric transformations involve altering the spatial arrangement of pixels within an image, such as downscale-upscale resampling, scaling, stretching, and translation, which improve the model's ability to generalize across various spatial configurations. Color space operations modify the color attributes of an image, including adjusting brightness, color balance, contrast, equalizing the histogram, and applying color filters. These changes help the model become robust against variations in lighting and color distribution.
            <br><br>
            <h3>Data Collection and Processing</h3>
            The 3D models were placed against 100+ HDRI backdrops, with variations in exposure levels to capture diverse lighting conditions. A camera within the Unity scene, positioned at random angles and distances, captured these setups. The Unity game engine collected data as a CSV file. The Unity game engine collected data as a CSV file, which we then augmented with various color space and geometrical operations, resulting in a new CSV file containing all the augmentation information. In the end, the entire dataframe was converted to COCO JSON format, a widely used format for object detection that includes detailed annotations for each image. While creating this comprehensive pipeline, I was responsible for conducting a literature survey to determine how to categorize skin tones, selecting appropriate data augmentation methods, collecting and managing the data as a CSV, and developing a data-in data-out pipeline that ultimately outputs the COCO JSON format compatible with our HRNet architecture.
            <br><br>
            <h3>Results</h3>
            The culmination of these efforts resulted in Hi5 - an unlimited generator of unique hand images, capable of creating approximately 500,000 images in 24 hours. A task generally considered expensive and time-consuming became both cost-effective and efficient, with the cost reduced to mere electricity charges for running the system and the process speed increased to just a few hours.
            <br><br>
            <h3>Hand Detection and Pose Estimation</h3>
            To find the hand bounding boxes in the captured footage, we used hand detection models based on the University of Michigan's Fouhey Lab's '100 days of hand' dataset. I trained the YOLOv7 model for hand detection, which identified the bounding boxes, allowing us to zoom into those regions. With the pipeline in place, HRNet's architecture was trained on this synthetic dataset. Subsequently, the emergence of the VitPose paper led us to train an improved model using VitPose, culminating in achieving a Percentage of Correct Keypoints (PCK) of 96.08%.
            <br><br>
            <h3>Conclusion and Future Directions</h3>
            Months of iterative refining of our dataset and pipeline led to successful tracking of fingers, even when hands were partially leaving the frame. However, we also identified limitations that opened new avenues for future exploration. While making a direct comparison to the current state-of-the-art was challenging due to the domain gap between 'in-the-wild' environments and synthetic environments, we confirmed synthetic data's efficacy. The Hi5 project highlights the strides made in advancing hand pose estimation research, delivering a foundation for using synthetic data in niches where data scarcity is a prominent concern.
        </p>`
    },
    {
        id: 3,
        title: "Past World Navigator",
        type: "Personal Project",
        thumbnail: "../../files/img/projects/project_3_thumbnail.png",
        content: `
        <p>
            Feel free to contact me for beta access.
            <h3>Introduction</h3>
            Past World Navigator is a digital platform that enables users to explore a 3D model of the world, travel through time, and experience historically accurate city recreations. The inspiration came from a casual exploration of Google Maps' street view. I was curious about how much of my room's window was visible and pondered the year it was captured. Different places have been photographed at different times, and some locations have multiple captures spanning decades, allowing us to see how they have evolved. This sparked a question in my mind: Could I do this for any place and any year? What if I could go back to the year 1234 and see what Egypt was like? While history often focuses on significant events, I wanted to offer a perspective for those who simply wish to understand what everyday life was like at any time and place. Although we lack the data to recreate every single detail, I believed that by narrowing the scope, we could capture the essence and provide a solid representation of the past, offering the closest experience to traveling through time.
            <br><br>
            <h3>Design Process</h3>
            Navigating the project presented a significant learning curve, particularly in breaking down the task into manageable components within the Unreal Engine framework, a platform with which I had familiarity but not extensive experience in development. I divided the platform into two primary views: Globe View and Landscape View. In Globe View, users interact with a 3D model of the world represented as a sphere, featuring a year slider for time travel and the ability to click on cities to access basic statistical data. Transitioning to Landscape View, users immerse themselves in first-person exploration of historically accurate city representations.
            <br><br>
            <h3>Development Approach</h3>
            I initially narrowed the project scope to focus on country-level exploration rather than city-level detail, prioritizing development progress over extensive data collection. Integrating country borders proved to be a crucial step, and after researching, I found GeoJSON files to be a valuable resource. These files allowed me to texture the earth mesh with country borders using Bresenham's line algorithm, laying the foundation for user interaction. However, enabling users to click on countries required a method to determine mouse hover locations. To achieve this, I utilized UV coordinates to map mouse positions to the texture. Additionally, I rasterized GeoJSON data into a bin file, enabling efficient storage and retrieval of country information. Implementing a flood-fill algorithm highlighted selected countries, enhancing user interaction. Establishing the core gameplay loop—navigating the globe, selecting countries, transitioning to first-person exploration, and returning—was a significant milestone. However, the prospect of manually creating 3D environments for every country and year was daunting in terms of time and resources. Procedural generation emerged as the solution, leading to the next phase of development: defining country representation and implementing procedural world generation.
            <br><br>
            <h3>Representation and Procedural Generation</h3>
            If you were transported back to a random year and place, how would you know where you are? People's clothing? Architectural style? This question spurred ideas on how to best represent and capture a specific time and place. For procedural generation, I decided to break down a country into nine key elements, arranged in a 3x3 grid. These elements include Agriculture, Mining Field, Factory, Landmark, Government, Religion, Residential Area, Downtown, and Education Level. By developing each of these elements separately and creating variations for each, I could utilize textual data about the country and era to procedurally generate a comprehensive map. This approach allows for dynamically constructed environments that reflect the historical context of any given time and place.
            <br><br>
            <h3>Defining Regions and Data Consistency</h3>
            What counts as a country? The USA and Spain are clear examples, while Greenland and Bermuda are recognized as territories. But what about 5000 years ago? Egypt was a nation with defined borders and a centralized government, but what about the Afanasievo culture? To accurately break down the world into regions at any given year, we need a flexible approach since not every society existed within recognized borders, and there is no definitive list. Currently, as of June 2024, the goal is to create a proof of concept for the modern world, focusing on the 193 countries recognized by the United Nations. However, historical and geographical data are often inconsistent. GeoJSON data, for example, includes separate entries for small islands owned by countries and lists the same country under different names, such as South Korea and the Republic of Korea. This necessitated extensive data cleaning to ensure uniformity, so the world is consistently divided into the same number of regions, with standardized names for each country.
            <br><br>
            <h3>Data Collection and Credibility</h3>
            The current data collection approach involves curating a comprehensive information base about history, drawing from sources such as Wikipedia, textbooks, and national archives. By utilizing a vector database, we can gather specific information about each country at any given time. This method not only allows for the detailed representation of historical data but also ensures that the information is easily citable. Users can assess the credibility of the sources, enhancing the educational value and reliability of the platform.
            <br><br>
            <h3>3D Modeling and Environment Art</h3>
            The other key aspect of the project is 3D modeling and environment art. As a solo developer, my focus is on overall development rather than getting bogged down with specific parts of the project for extended periods. While delays might still occur, it's crucial to ensure that the time invested translates into tangible progress within the project. To manage this, I utilize a platform that allows me to create AI-generated 3D meshes using text prompts. Although the AI output is not yet refined enough for the final product, it serves as an excellent tool for visualizing potential worlds and experimenting with different layouts. This approach allows me to rapidly prototype and iterate without the risk of wasting weeks on models that might not make it into the final version.
            <br><br>
            <h3>Expanding Features and Future Goals</h3>
            In addition to the core functionalities, other work includes implementing gamepad support for a release on Steam, aiming to attract a gamer audience similar to educational tools like SpaceEngine, which offers a 1:1 recreation of the universe for observational purposes. VR support has also been added to enhance the immersiveness of the environments. Currently, the platform is available on Steam for beta testers, whose feedback, along with drawn prototypes, helps refine the UI/UX for this type of application. The immediate goal is to finalize the dataset and integrate everything to enable exploration of the modern world using my concept. The next steps involve expanding to historical times and providing city-level information using the previously mentioned data collection pipeline. If the product is successful, I plan to write a paper detailing the pipeline and conduct a pilot study with students to test the platform's effectiveness in learning, which will result in a separate research paper.
            <br><br>
            <h3>Conclusion</h3>
            Past World Navigator represents an innovative approach to exploring and understanding history through an immersive 3D platform that facilitates temporal and spatial travel. By integrating procedural generation, comprehensive data collection, and advanced technologies such as VR and AI-driven 3D modeling, the platform offers a unique intersection of education and interactive engagement. The iterative development process, informed by user feedback and a commitment to historical accuracy, ensures the project's continual enhancement. As the development progresses, the objective is to broaden the temporal and spatial scope of the exploration, optimize the user interface, and rigorously assess the platform's educational efficacy. Ultimately, Past World Navigator aspires to become a valuable tool for both educational purposes and historical research, providing users with an in-depth and dynamic means of engaging with the past.
        </p>`
    },
    {
        id: 4,
        title: "BrawlNet - Deep Reinforcement Learning for Brawlhalla",
        type: "Personal Project",
        thumbnail: "../../files/img/projects/project_4_thumbnail.png",
        content: `
        <p>
            <h3>Introduction</h3>
            BrawlNet is a deep reinforcement learning model that is aimed to be capable of playing the video game "Brawlhalla" with proficiency comparable to human players. This work originated from my enjoyment of the game, which I frequently played with a friend who is often better at it than me. I wondered if I could train an AI to play the game and beat him as a harmless prank, with no intention of using the AI in online lobbies. "Brawlhalla" operates in a dynamic, fast-paced, 2D platform fighting game environment that requires strategic real-time decision-making. My primary goal was to construct an AI agent that could understand and navigate the gameplay as proficiently as humans do, using reinforcement learning and convolutional neural networks.
            <br><br>
            <h3>Initial Approach</h3>
            The initial idea was to create a synthetic image dataset where I randomly placed a player character on a random location of a map with random health values. This dataset would facilitate the training of a game state detector model capable of assessing real game screenshots. Subsequently, this detector would enable the training of a second AI that would watch Brawlhalla championship videos to learn top-level gameplay. This approach would have been simpler with real-time mouse input data from users, but such data is typically absent in professional gameplay videos, necessitating inferences based on the kinematic motions of characters. Recognizing the complexity of this approach, I decided to change my strategy.
            <br><br>
            <h3>Model Design</h3>
            The core of the project involved capturing and decoding real-time game state data effectively. This data, in the form of screenshots, served as a means for the AI agent to comprehend the virtual environment. Each screenshot was downscaled to a fixed size, greyscaled, and then normalized to reduce computation load. The processed set of preceding five frames was then input into the designed model, termed 'BrawlNet', a convolutional neural network specifically outfitted for understanding motion and action consequences. To facilitate faster training, the game's tick speed was increased 20 times, allowing the AI to process and learn from game states more efficiently.
            <br><br>
            BrawlNet accepts stacked grayscale images as inputs, processes them through multiple convolutional layers to extract meaningful data and interpret game dynamics. Each layer consists of an increasing number of filters for detailed and comprehensive learning of attributes from the game's state images. Following the processing, an output layer generates 21 distinct potential actions corresponding to distinct game controls such as movement and attack options.
            <br><br>
            Adapting to a constant learning curve, the RL algorithm is a variant of policy gradient methods. The choice of this method was primarily driven by the necessity for the model to make decisions in a continuous action space, learning from delayed rewards. The AI agent received feedback from the reward function based on various in-game events like knockouts, damage taken or dealt, and falls.
            <br><br>
            <h3>Testing and Challenges</h3>
            Upon testing the model for numerous episodes, the AI showed gradual improvement in understanding the gameplay dynamics, adapting to playing styles, evading attacks, and targeting opponents. However, after 8 hours of training, the agent was only slightly better, indicating that further improvements were needed. One of the next goals is to initially train the model using my own gameplay, providing a quick-start understanding of actions that yield high rewards and those that result in negative rewards. After this initial phase, the AI will continue to train on its own to further accelerate learning. Additionally, another approach to be tested is increasing the game tick speed even further and parallelizing the training process to expedite learning and enhance the AI's performance.
            <br><br>
            <h3>Conclusion</h3>
            The project foregrounds potential future work, including integrating recurrent neural networks to enhance temporal understanding, experimenting with advanced RL algorithms like Proximal Policy Optimization, and ongoing adjustments of the model's hyperparameters based on performance metrics. While challenging on many fronts, this project solidifies a significant stride toward the application of deep reinforcement learning in intricate real-time game settings. Despite certain limitations, it has demonstrated promising progress in developing sophisticated AI gaming agents.
        </p>`
    }
];
